---
apiVersion: v1
kind: Service
metadata:
  name: tbtc-dapp
  namespace: default
  annotations:
  labels:
    app: tbtc
    type: dapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: https-80
  selector:
    app: tbtc
    type: dapp
