---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tbtc-dapp-http
  namespace: tbtc
  labels:
    app: tbtc
    type: dapp
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
spec:
  backend:
    # This assumes service eth-dashboard-http exists and routes to healthy endpoints
    serviceName: tbtc-dapp-http
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tbtc-dapp-http
  namespace: tbtc
  labels:
    app: tbtc
    type: dapp
spec:
  type: NodePort
  ports:
  - name: tbtc-dapp-http-port
    port: 80
    targetPort: 80
  selector:
    app: tbtc
    type: dapp